AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  powertools-examples-cloudformation
  Sample SAM Template for powertools-examples-cloudformation

Globals:
  Function:
    Timeout: 20

Parameters:
  pApplicationName:
    Type: String

Resources:
  HelloWorldCustomResource:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !GetAtt 'HelloWorldFunction.Arn'
      ApplicationName: !Ref 'pApplicationName'

  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../../
      Handler: app.nymbl.customresource.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        - Statement:
            - Sid: elasticbeanstalkcustomaccess1
              Effect: Allow
              Action:
                - elasticbeanstalk:DescribeApplications
              Resource: '*'
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

